# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mki180v1_driver


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += mbed/drivers/AnalogIn.o
OBJECTS += mbed/drivers/BusIn.o
OBJECTS += mbed/drivers/BusInOut.o
OBJECTS += mbed/drivers/BusOut.o
OBJECTS += mbed/drivers/CAN.o
OBJECTS += mbed/drivers/Ethernet.o
OBJECTS += mbed/drivers/FlashIAP.o
OBJECTS += mbed/drivers/I2C.o
OBJECTS += mbed/drivers/I2CSlave.o
OBJECTS += mbed/drivers/InterruptIn.o
OBJECTS += mbed/drivers/InterruptManager.o
OBJECTS += mbed/drivers/MbedCRC.o
OBJECTS += mbed/drivers/RawSerial.o
OBJECTS += mbed/drivers/SPI.o
OBJECTS += mbed/drivers/SPISlave.o
OBJECTS += mbed/drivers/Serial.o
OBJECTS += mbed/drivers/SerialBase.o
OBJECTS += mbed/drivers/TableCRC.o
OBJECTS += mbed/drivers/Ticker.o
OBJECTS += mbed/drivers/Timeout.o
OBJECTS += mbed/drivers/Timer.o
OBJECTS += mbed/drivers/TimerEvent.o
OBJECTS += mbed/drivers/UARTSerial.o
OBJECTS += mbed/events/EventQueue.o
OBJECTS += mbed/events/equeue/equeue.o
OBJECTS += mbed/events/equeue/equeue_mbed.o
OBJECTS += mbed/events/equeue/equeue_posix.o
OBJECTS += mbed/events/mbed_shared_queues.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/EthernetInterface.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/emac_lwip.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/emac_stack_lwip.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/stm32f7_eth_init.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/stm32f7_eth_conf.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_checksum.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_memcpy.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_random.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_tcp_isn.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_api_lib.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_api_msg.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_err.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netbuf.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netdb.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netifapi.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_sockets.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_tcpip.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_autoip.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_dhcp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_etharp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_icmp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_igmp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4_addr.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4_frag.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_dhcp6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ethip6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_icmp6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_inet6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6_addr.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6_frag.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_mld6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_nd6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_def.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_dns.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_inet_chksum.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_init.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_ip.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_mem.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_memp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_netif.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_pbuf.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_raw.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_stats.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_sys.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp_in.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp_out.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_timeouts.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_udp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_ethernet.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_ethernetif.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_lowpan6.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_auth.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ccp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap-md5.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap-new.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap_ms.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_demand.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_eap.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ecp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_eui64.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_fsm.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ipcp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ipv6cp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_lcp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_magic.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_mppe.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_multilink.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ppp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppapi.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppcrypt.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppoe.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppol2tp.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppos.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_upap.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_utils.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_vj.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_arc4.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_des.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_md4.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_md5.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_sha1.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/lwip_stack.o
OBJECTS += mbed/features/FEATURE_LWIP/lwip-interface/ppp_lwip.o
OBJECTS += mbed/features/cellular/easy_cellular/CellularConnectionFSM.o
OBJECTS += mbed/features/cellular/easy_cellular/EasyCellularConnection.o
OBJECTS += mbed/features/cellular/framework/AT/ATHandler.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularBase.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularDevice.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularInformation.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularNetwork.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularPower.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularSIM.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularSMS.o
OBJECTS += mbed/features/cellular/framework/AT/AT_CellularStack.o
OBJECTS += mbed/features/cellular/framework/common/CellularUtil.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.o
OBJECTS += mbed/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.o
OBJECTS += mbed/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.o
OBJECTS += mbed/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.o
OBJECTS += mbed/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.o
OBJECTS += mbed/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U.o
OBJECTS += mbed/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularNetwork.o
OBJECTS += mbed/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularPower.o
OBJECTS += mbed/features/filesystem/Dir.o
OBJECTS += mbed/features/filesystem/File.o
OBJECTS += mbed/features/filesystem/FileSystem.o
OBJECTS += mbed/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/ExhaustibleBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/MBRBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/ObservingBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/ProfilingBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/ReadOnlyBlockDevice.o
OBJECTS += mbed/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += mbed/features/filesystem/fat/ChaN/ff.o
OBJECTS += mbed/features/filesystem/fat/ChaN/ffunicode.o
OBJECTS += mbed/features/filesystem/fat/FATFileSystem.o
OBJECTS += mbed/features/filesystem/littlefs/LittleFileSystem.o
OBJECTS += mbed/features/filesystem/littlefs/littlefs/lfs.o
OBJECTS += mbed/features/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += mbed/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += mbed/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += mbed/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += mbed/features/frameworks/unity/source/unity.o
OBJECTS += mbed/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += mbed/features/frameworks/utest/source/unity_handler.o
OBJECTS += mbed/features/frameworks/utest/source/utest_case.o
OBJECTS += mbed/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += mbed/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += mbed/features/frameworks/utest/source/utest_harness.o
OBJECTS += mbed/features/frameworks/utest/source/utest_shim.o
OBJECTS += mbed/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += mbed/features/frameworks/utest/source/utest_types.o
OBJECTS += mbed/features/lorawan/LoRaWANInterface.o
OBJECTS += mbed/features/lorawan/LoRaWANStack.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMac.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacChannelPlan.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacCommand.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacCrypto.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacMcps.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacMib.o
OBJECTS += mbed/features/lorawan/lorastack/mac/LoRaMacMlme.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHY.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYAS923.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYAU915.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYCN470.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYCN779.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYEU433.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYEU868.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYIN865.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYKR920.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYUS915.o
OBJECTS += mbed/features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.o
OBJECTS += mbed/features/lorawan/system/LoRaWANTimer.o
OBJECTS += mbed/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += mbed/features/mbedtls/src/aes.o
OBJECTS += mbed/features/mbedtls/src/aesni.o
OBJECTS += mbed/features/mbedtls/src/arc4.o
OBJECTS += mbed/features/mbedtls/src/asn1parse.o
OBJECTS += mbed/features/mbedtls/src/asn1write.o
OBJECTS += mbed/features/mbedtls/src/base64.o
OBJECTS += mbed/features/mbedtls/src/bignum.o
OBJECTS += mbed/features/mbedtls/src/blowfish.o
OBJECTS += mbed/features/mbedtls/src/camellia.o
OBJECTS += mbed/features/mbedtls/src/ccm.o
OBJECTS += mbed/features/mbedtls/src/certs.o
OBJECTS += mbed/features/mbedtls/src/cipher.o
OBJECTS += mbed/features/mbedtls/src/cipher_wrap.o
OBJECTS += mbed/features/mbedtls/src/cmac.o
OBJECTS += mbed/features/mbedtls/src/ctr_drbg.o
OBJECTS += mbed/features/mbedtls/src/debug.o
OBJECTS += mbed/features/mbedtls/src/des.o
OBJECTS += mbed/features/mbedtls/src/dhm.o
OBJECTS += mbed/features/mbedtls/src/ecdh.o
OBJECTS += mbed/features/mbedtls/src/ecdsa.o
OBJECTS += mbed/features/mbedtls/src/ecjpake.o
OBJECTS += mbed/features/mbedtls/src/ecp.o
OBJECTS += mbed/features/mbedtls/src/ecp_curves.o
OBJECTS += mbed/features/mbedtls/src/entropy.o
OBJECTS += mbed/features/mbedtls/src/entropy_poll.o
OBJECTS += mbed/features/mbedtls/src/error.o
OBJECTS += mbed/features/mbedtls/src/gcm.o
OBJECTS += mbed/features/mbedtls/src/havege.o
OBJECTS += mbed/features/mbedtls/src/hmac_drbg.o
OBJECTS += mbed/features/mbedtls/src/md.o
OBJECTS += mbed/features/mbedtls/src/md2.o
OBJECTS += mbed/features/mbedtls/src/md4.o
OBJECTS += mbed/features/mbedtls/src/md5.o
OBJECTS += mbed/features/mbedtls/src/md_wrap.o
OBJECTS += mbed/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += mbed/features/mbedtls/src/net_sockets.o
OBJECTS += mbed/features/mbedtls/src/oid.o
OBJECTS += mbed/features/mbedtls/src/padlock.o
OBJECTS += mbed/features/mbedtls/src/pem.o
OBJECTS += mbed/features/mbedtls/src/pk.o
OBJECTS += mbed/features/mbedtls/src/pk_wrap.o
OBJECTS += mbed/features/mbedtls/src/pkcs11.o
OBJECTS += mbed/features/mbedtls/src/pkcs12.o
OBJECTS += mbed/features/mbedtls/src/pkcs5.o
OBJECTS += mbed/features/mbedtls/src/pkparse.o
OBJECTS += mbed/features/mbedtls/src/pkwrite.o
OBJECTS += mbed/features/mbedtls/src/platform.o
OBJECTS += mbed/features/mbedtls/src/ripemd160.o
OBJECTS += mbed/features/mbedtls/src/rsa.o
OBJECTS += mbed/features/mbedtls/src/rsa_internal.o
OBJECTS += mbed/features/mbedtls/src/sha1.o
OBJECTS += mbed/features/mbedtls/src/sha256.o
OBJECTS += mbed/features/mbedtls/src/sha512.o
OBJECTS += mbed/features/mbedtls/src/ssl_cache.o
OBJECTS += mbed/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += mbed/features/mbedtls/src/ssl_cli.o
OBJECTS += mbed/features/mbedtls/src/ssl_cookie.o
OBJECTS += mbed/features/mbedtls/src/ssl_srv.o
OBJECTS += mbed/features/mbedtls/src/ssl_ticket.o
OBJECTS += mbed/features/mbedtls/src/ssl_tls.o
OBJECTS += mbed/features/mbedtls/src/threading.o
OBJECTS += mbed/features/mbedtls/src/timing.o
OBJECTS += mbed/features/mbedtls/src/version.o
OBJECTS += mbed/features/mbedtls/src/version_features.o
OBJECTS += mbed/features/mbedtls/src/x509.o
OBJECTS += mbed/features/mbedtls/src/x509_create.o
OBJECTS += mbed/features/mbedtls/src/x509_crl.o
OBJECTS += mbed/features/mbedtls/src/x509_crt.o
OBJECTS += mbed/features/mbedtls/src/x509_csr.o
OBJECTS += mbed/features/mbedtls/src/x509write_crt.o
OBJECTS += mbed/features/mbedtls/src/x509write_csr.o
OBJECTS += mbed/features/mbedtls/src/xtea.o
OBJECTS += mbed/features/mbedtls/targets/TARGET_STM/aes_alt.o
OBJECTS += mbed/features/mbedtls/targets/TARGET_STM/md5_alt.o
OBJECTS += mbed/features/mbedtls/targets/TARGET_STM/sha1_alt.o
OBJECTS += mbed/features/mbedtls/targets/TARGET_STM/sha256_alt.o
OBJECTS += mbed/features/mbedtls/targets/hash_wrappers.o
OBJECTS += mbed/features/netsocket/NetworkInterface.o
OBJECTS += mbed/features/netsocket/NetworkStack.o
OBJECTS += mbed/features/netsocket/Socket.o
OBJECTS += mbed/features/netsocket/SocketAddress.o
OBJECTS += mbed/features/netsocket/TCPServer.o
OBJECTS += mbed/features/netsocket/TCPSocket.o
OBJECTS += mbed/features/netsocket/UDPSocket.o
OBJECTS += mbed/features/netsocket/WiFiAccessPoint.o
OBJECTS += mbed/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.o
OBJECTS += mbed/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.o
OBJECTS += mbed/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.o
OBJECTS += mbed/features/netsocket/nsapi_dns.o
OBJECTS += mbed/features/nvstore/source/nvstore.o
OBJECTS += mbed/hal/mbed_critical_section_api.o
OBJECTS += mbed/hal/mbed_flash_api.o
OBJECTS += mbed/hal/mbed_gpio.o
OBJECTS += mbed/hal/mbed_itm_api.o
OBJECTS += mbed/hal/mbed_lp_ticker_api.o
OBJECTS += mbed/hal/mbed_pinmap_common.o
OBJECTS += mbed/hal/mbed_sleep_manager.o
OBJECTS += mbed/hal/mbed_ticker_api.o
OBJECTS += mbed/hal/mbed_us_ticker_api.o
OBJECTS += mbed/platform/ATCmdParser.o
OBJECTS += mbed/platform/CallChain.o
OBJECTS += mbed/platform/FileBase.o
OBJECTS += mbed/platform/FileHandle.o
OBJECTS += mbed/platform/FilePath.o
OBJECTS += mbed/platform/FileSystemHandle.o
OBJECTS += mbed/platform/LocalFileSystem.o
OBJECTS += mbed/platform/Stream.o
OBJECTS += mbed/platform/mbed_alloc_wrappers.o
OBJECTS += mbed/platform/mbed_application.o
OBJECTS += mbed/platform/mbed_assert.o
OBJECTS += mbed/platform/mbed_board.o
OBJECTS += mbed/platform/mbed_critical.o
OBJECTS += mbed/platform/mbed_error.o
OBJECTS += mbed/platform/mbed_interface.o
OBJECTS += mbed/platform/mbed_mem_trace.o
OBJECTS += mbed/platform/mbed_mktime.o
OBJECTS += mbed/platform/mbed_poll.o
OBJECTS += mbed/platform/mbed_retarget.o
OBJECTS += mbed/platform/mbed_rtc_time.o
OBJECTS += mbed/platform/mbed_sdk_boot.o
OBJECTS += mbed/platform/mbed_semihost_api.o
OBJECTS += mbed/platform/mbed_stats.o
OBJECTS += mbed/platform/mbed_wait_api_no_rtos.o
OBJECTS += mbed/platform/mbed_wait_api_rtos.o
OBJECTS += mbed/rtos/ConditionVariable.o
OBJECTS += mbed/rtos/EventFlags.o
OBJECTS += mbed/rtos/Kernel.o
OBJECTS += mbed/rtos/Mutex.o
OBJECTS += mbed/rtos/RtosTimer.o
OBJECTS += mbed/rtos/Semaphore.o
OBJECTS += mbed/rtos/TARGET_CORTEX/SysTimer.o
OBJECTS += mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.o
OBJECTS += mbed/rtos/TARGET_CORTEX/mbed_boot.o
OBJECTS += mbed/rtos/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += mbed/rtos/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += mbed/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += mbed/rtos/Thread.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/analogin_device.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/analogout_device.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can_legacy.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cec.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cortex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dfsdm.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma2d.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dsi.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_gpio.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2s.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_irda.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_iwdg.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_jpeg.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_lptim.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mdios.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mmc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nand.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nor.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_qspi.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rng.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sd.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sdram.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smbus.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spdifrx.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sram.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim_ex.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_uart.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_usart.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_wwdg.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_adc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_crc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dac.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma2d.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_exti.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_fmc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_gpio.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_i2c.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_lptim.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_pwr.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rcc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rng.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rtc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_sdmmc.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_spi.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_tim.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usart.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_utils.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/device/system_stm32f7xx.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/flash_api.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/serial_device.o
OBJECTS += mbed/targets/TARGET_STM/TARGET_STM32F7/spi_api.o
OBJECTS += mbed/targets/TARGET_STM/analogin_api.o
OBJECTS += mbed/targets/TARGET_STM/analogout_api.o
OBJECTS += mbed/targets/TARGET_STM/can_api.o
OBJECTS += mbed/targets/TARGET_STM/gpio_api.o
OBJECTS += mbed/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += mbed/targets/TARGET_STM/hal_tick_16b.o
OBJECTS += mbed/targets/TARGET_STM/hal_tick_32b.o
OBJECTS += mbed/targets/TARGET_STM/i2c_api.o
OBJECTS += mbed/targets/TARGET_STM/lp_ticker.o
OBJECTS += mbed/targets/TARGET_STM/mbed_overrides.o
OBJECTS += mbed/targets/TARGET_STM/pinmap.o
OBJECTS += mbed/targets/TARGET_STM/port_api.o
OBJECTS += mbed/targets/TARGET_STM/pwmout_api.o
OBJECTS += mbed/targets/TARGET_STM/rtc_api.o
OBJECTS += mbed/targets/TARGET_STM/serial_api.o
OBJECTS += mbed/targets/TARGET_STM/sleep.o
OBJECTS += mbed/targets/TARGET_STM/stm_spi_api.o
OBJECTS += mbed/targets/TARGET_STM/trng_api.o
OBJECTS += mbed/targets/TARGET_STM/us_ticker_16b.o
OBJECTS += mbed/targets/TARGET_STM/us_ticker_32b.o
OBJECTS += src/main.o
OBJECTS += src/mki180.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../mbed/.
INCLUDE_PATHS += -I../mbed/cmsis
INCLUDE_PATHS += -I../mbed/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed/drivers
INCLUDE_PATHS += -I../mbed/events
INCLUDE_PATHS += -I../mbed/events/equeue
INCLUDE_PATHS += -I../mbed/features
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp
INCLUDE_PATHS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl
INCLUDE_PATHS += -I../mbed/features/cellular
INCLUDE_PATHS += -I../mbed/features/cellular/easy_cellular
INCLUDE_PATHS += -I../mbed/features/cellular/framework
INCLUDE_PATHS += -I../mbed/features/cellular/framework/API
INCLUDE_PATHS += -I../mbed/features/cellular/framework/AT
INCLUDE_PATHS += -I../mbed/features/cellular/framework/common
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/QUECTEL
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/QUECTEL/BC95
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/QUECTEL/BG96
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/TELIT
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/TELIT/HE910
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/UBLOX
INCLUDE_PATHS += -I../mbed/features/cellular/framework/targets/UBLOX/LISA_U
INCLUDE_PATHS += -I../mbed/features/filesystem
INCLUDE_PATHS += -I../mbed/features/filesystem/bd
INCLUDE_PATHS += -I../mbed/features/filesystem/fat
INCLUDE_PATHS += -I../mbed/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I../mbed/features/filesystem/littlefs
INCLUDE_PATHS += -I../mbed/features/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I../mbed/features/frameworks
INCLUDE_PATHS += -I../mbed/features/frameworks/greentea-client
INCLUDE_PATHS += -I../mbed/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I../mbed/features/frameworks/greentea-client/source
INCLUDE_PATHS += -I../mbed/features/frameworks/unity
INCLUDE_PATHS += -I../mbed/features/frameworks/unity/source
INCLUDE_PATHS += -I../mbed/features/frameworks/unity/unity
INCLUDE_PATHS += -I../mbed/features/frameworks/utest
INCLUDE_PATHS += -I../mbed/features/frameworks/utest/source
INCLUDE_PATHS += -I../mbed/features/frameworks/utest/utest
INCLUDE_PATHS += -I../mbed/features/lorawan
INCLUDE_PATHS += -I../mbed/features/lorawan/lorastack
INCLUDE_PATHS += -I../mbed/features/lorawan/lorastack/mac
INCLUDE_PATHS += -I../mbed/features/lorawan/lorastack/phy
INCLUDE_PATHS += -I../mbed/features/lorawan/system
INCLUDE_PATHS += -I../mbed/features/mbedtls
INCLUDE_PATHS += -I../mbed/features/mbedtls/importer
INCLUDE_PATHS += -I../mbed/features/mbedtls/inc
INCLUDE_PATHS += -I../mbed/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I../mbed/features/mbedtls/platform
INCLUDE_PATHS += -I../mbed/features/mbedtls/platform/inc
INCLUDE_PATHS += -I../mbed/features/mbedtls/platform/src
INCLUDE_PATHS += -I../mbed/features/mbedtls/src
INCLUDE_PATHS += -I../mbed/features/mbedtls/targets
INCLUDE_PATHS += -I../mbed/features/mbedtls/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed/features/mbedtls/targets/TARGET_STM/TARGET_STM32F7
INCLUDE_PATHS += -I../mbed/features/nanostack
INCLUDE_PATHS += -I../mbed/features/netsocket
INCLUDE_PATHS += -I../mbed/features/netsocket/cellular
INCLUDE_PATHS += -I../mbed/features/netsocket/cellular/generic_modem_driver
INCLUDE_PATHS += -I../mbed/features/nvstore
INCLUDE_PATHS += -I../mbed/features/nvstore/source
INCLUDE_PATHS += -I../mbed/features/storage
INCLUDE_PATHS += -I../mbed/hal
INCLUDE_PATHS += -I../mbed/hal/storage_abstraction
INCLUDE_PATHS += -I../mbed/platform
INCLUDE_PATHS += -I../mbed/rtos
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
INCLUDE_PATHS += -I../mbed/rtos/TARGET_CORTEX/rtx5/Source
INCLUDE_PATHS += -I../mbed/targets
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/device
INCLUDE_PATHS += -I../src

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/STM32F767xI.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m7' '-mthumb' '-mfpu=fpv5-d16' '-mfloat-abi=softfp'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m7' '-mthumb' '-mfpu=fpv5-d16' '-mfloat-abi=softfp'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m7' '-mthumb' '-mfpu=fpv5-d16' '-mfloat-abi=softfp'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '-mcpu=cortex-m7' '-mthumb' '-mfpu=fpv5-d16' '-mfloat-abi=softfp'


C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DFEATURE_LWIP=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DTARGET_STM32F767ZI
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DTARGET_STM32F7
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DARM_MATH_CM7
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_LIKE_CORTEX_M7
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DTARGET_NUCLEO_F767ZI
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_M7
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -D__CORTEX_M7
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DTARGET_FAMILY_STM32
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_STM32F767
C_FLAGS += -DTARGET_STM
C_FLAGS += -DUSBHOST_OTHER
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DTARGET_STM32F767xI
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1525248461.36
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DFEATURE_LWIP=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DTARGET_STM32F767ZI
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DTARGET_STM32F7
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DARM_MATH_CM7
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M7
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DTARGET_NUCLEO_F767ZI
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_M7
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -D__CORTEX_M7
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DTARGET_FAMILY_STM32
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_STM32F767
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DUSBHOST_OTHER
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DTARGET_STM32F767xI
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1525248461.36
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -D__CORTEX_M7
ASM_FLAGS += -DARM_MATH_CM7
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DUSBHOST_OTHER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -I../.
ASM_FLAGS += -I../src
ASM_FLAGS += -I../mbed/.
ASM_FLAGS += -I../mbed/features
ASM_FLAGS += -I../mbed/features/frameworks
ASM_FLAGS += -I../mbed/features/frameworks/greentea-client
ASM_FLAGS += -I../mbed/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -I../mbed/features/frameworks/greentea-client/source
ASM_FLAGS += -I../mbed/features/frameworks/unity
ASM_FLAGS += -I../mbed/features/frameworks/unity/source
ASM_FLAGS += -I../mbed/features/frameworks/unity/unity
ASM_FLAGS += -I../mbed/features/frameworks/utest
ASM_FLAGS += -I../mbed/features/frameworks/utest/source
ASM_FLAGS += -I../mbed/features/frameworks/utest/utest
ASM_FLAGS += -I../mbed/features/mbedtls
ASM_FLAGS += -I../mbed/features/mbedtls/importer
ASM_FLAGS += -I../mbed/features/mbedtls/inc
ASM_FLAGS += -I../mbed/features/mbedtls/inc/mbedtls
ASM_FLAGS += -I../mbed/features/mbedtls/src
ASM_FLAGS += -I../mbed/features/mbedtls/platform
ASM_FLAGS += -I../mbed/features/mbedtls/platform/inc
ASM_FLAGS += -I../mbed/features/mbedtls/platform/src
ASM_FLAGS += -I../mbed/features/mbedtls/targets
ASM_FLAGS += -I../mbed/features/mbedtls/targets/TARGET_STM
ASM_FLAGS += -I../mbed/features/mbedtls/targets/TARGET_STM/TARGET_STM32F7
ASM_FLAGS += -I../mbed/features/nanostack
ASM_FLAGS += -I../mbed/features/storage
ASM_FLAGS += -I../mbed/features/netsocket
ASM_FLAGS += -I../mbed/features/netsocket/cellular
ASM_FLAGS += -I../mbed/features/netsocket/cellular/generic_modem_driver
ASM_FLAGS += -I../mbed/features/filesystem
ASM_FLAGS += -I../mbed/features/filesystem/bd
ASM_FLAGS += -I../mbed/features/filesystem/fat
ASM_FLAGS += -I../mbed/features/filesystem/fat/ChaN
ASM_FLAGS += -I../mbed/features/filesystem/littlefs
ASM_FLAGS += -I../mbed/features/filesystem/littlefs/littlefs
ASM_FLAGS += -I../mbed/features/cellular
ASM_FLAGS += -I../mbed/features/cellular/easy_cellular
ASM_FLAGS += -I../mbed/features/cellular/framework
ASM_FLAGS += -I../mbed/features/cellular/framework/API
ASM_FLAGS += -I../mbed/features/cellular/framework/AT
ASM_FLAGS += -I../mbed/features/cellular/framework/common
ASM_FLAGS += -I../mbed/features/cellular/framework/targets
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/QUECTEL
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/QUECTEL/BC95
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/QUECTEL/BG96
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/TELIT
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/TELIT/HE910
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/UBLOX
ASM_FLAGS += -I../mbed/features/cellular/framework/targets/UBLOX/LISA_U
ASM_FLAGS += -I../mbed/features/lorawan
ASM_FLAGS += -I../mbed/features/lorawan/lorastack
ASM_FLAGS += -I../mbed/features/lorawan/lorastack/mac
ASM_FLAGS += -I../mbed/features/lorawan/lorastack/phy
ASM_FLAGS += -I../mbed/features/lorawan/system
ASM_FLAGS += -I../mbed/features/nvstore
ASM_FLAGS += -I../mbed/features/nvstore/source
ASM_FLAGS += -I../mbed/cmsis
ASM_FLAGS += -I../mbed/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed/drivers
ASM_FLAGS += -I../mbed/events
ASM_FLAGS += -I../mbed/events/equeue
ASM_FLAGS += -I../mbed/rtos
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx4
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/Include
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Config
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Include
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/rtx5/Source
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC
ASM_FLAGS += -I../mbed/hal
ASM_FLAGS += -I../mbed/hal/storage_abstraction
ASM_FLAGS += -I../mbed/platform
ASM_FLAGS += -I../mbed/targets
ASM_FLAGS += -I../mbed/targets/TARGET_STM
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM
ASM_FLAGS += -I../mbed/targets/TARGET_STM/TARGET_STM32F7/device
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/api
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp
ASM_FLAGS += -I../mbed/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
